"use client";

import { useEffect } from "react";

import { m } from "framer-motion";

import {
  AlertTriangle,
    RefreshCcw,
      Home,
        Terminal,
        } from "lucide-react";

        import Link from "next/link";

        export default function Error({
          error,
            reset,
            }: {
              error: Error & { digest?: string };
                reset: () => void;
                }) {
                  useEffect(() => {
                      console.error("System Exception Logged:", error);
                        }, [error]);

                          return (
                              <main className="fixed inset-0 z-[150] bg-background flex items-center justify-center px-6 overflow-hidden">
                                    <div
                                            className="absolute inset-0 bg-grid opacity-30 pointer-events-none"
                                                    aria-hidden="true"
                                                          />

                                                                <div
                                                                        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-red-500/5 blur-[140px] rounded-full pointer-events-none"
                                                                                aria-hidden="true"
                                                                                      />

                                                                                            <m.div
                                                                                                    initial={{ opacity: 0 }}
                                                                                                            animate={{ opacity: 1 }}
                                                                                                                    className="relative z-10 w-full max-w-lg text-center space-y-8"
                                                                                                                          >
                                                                                                                                  <div className="flex justify-center">
                                                                                                                                            <div className="relative">
                                                                                                                                                        <m.div
                                                                                                                                                                      animate={{ opacity: [0.5, 1, 0.5] }}
                                                                                                                                                                                    transition={{ duration: 2, repeat: Infinity }}
                                                                                                                                                                                                  className="absolute -inset-4 bg-red-500/10 blur-xl rounded-full"
                                                                                                                                                                                                              />

                                                                                                                                                                                                                          <div className="relative w-16 h-16 rounded-xl bg-background border border-red-500/30 flex items-center justify-center text-red-500 shadow-lg shadow-red-500/10">
                                                                                                                                                                                                                                        <AlertTriangle size={32} />
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                        <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-white uppercase font-mono">
                                                                                                                                                                                                                                                                                                    Critical System <span className="text-red-500">Failure</span>
                                                                                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                                                                                        <p className="text-gray-500 text-xs md:text-sm font-mono leading-relaxed max-w-xs mx-auto uppercase">
                                                                                                                                                                                                                                                                                                                                    A fatal exception has occurred.
                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                              <div className="bg-panel/50 border border-red-500/20 rounded-lg p-4 text-left font-mono overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-2 mb-2 pb-2 border-b border-white/5">
                                                                                                                                                                                                                                                                                                                                                                                    <Terminal size={12} className="text-red-500" />

                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-[10px] text-gray-500 uppercase">
                                                                                                                                                                                                                                                                                                                                                                                                              Diagnostic Trace
                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[11px] text-red-400/80 break-all leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error.digest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? `ID: ${error.digest}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "ERROR_UNKNOWN_TERMINATION"}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <br />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error.message || "Failed to execute mission protocol."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => reset()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full sm:w-auto px-8 py-4 bg-white text-black font-bold rounded-lg flex items-center justify-center gap-3 hover:bg-emerald-primary hover:text-white transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <RefreshCcw size={18} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Retry Protocol
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full sm:w-auto px-8 py-4 bg-white/5 border border-white/10 text-white font-bold rounded-lg flex items-center justify-center gap-3 hover:bg-white/10 transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Home size={18} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Abort to Base
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </m.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }