"use client";

import { m } from "framer-motion";

import { Terminal } from "lucide-react";

export default function Loading() {
  return (
      <div className="fixed inset-0 z-[100] bg-background flex flex-col items-center justify-center overflow-hidden">
            {/* Grid */}
                  <div className="absolute inset-0 bg-grid opacity-20 pointer-events-none" />

                        {/* Center */}
                              <div className="relative z-10 flex flex-col items-center gap-6">
                                      <m.div
                                                initial={{
                                                            opacity: 0,
                                                                        scale: 0.9,
                                                                                  }}
                                                                                            animate={{
                                                                                                        opacity: 1,
                                                                                                                    scale: 1,
                                                                                                                              }}
                                                                                                                                        transition={{
                                                                                                                                                    duration: 0.5,
                                                                                                                                                              }}
                                                                                                                                                                        className="flex items-center gap-3"
                                                                                                                                                                                >
                                                                                                                                                                                          <Terminal
                                                                                                                                                                                                      size={20}
                                                                                                                                                                                                                  className="text-emerald-primary"
                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                      <span className="text-xs font-mono text-white uppercase tracking-[0.4em] font-bold">
                                                                                                                                                                                                                                                  System Boot
                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                    </m.div>

                                                                                                                                                                                                                                                                            {/* Loader */}
                                                                                                                                                                                                                                                                                    <div className="w-48 h-[2px] bg-white/5 rounded-full relative overflow-hidden">
                                                                                                                                                                                                                                                                                              <m.div
                                                                                                                                                                                                                                                                                                          initial={{
                                                                                                                                                                                                                                                                                                                        left: "-100%",
                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                animate={{
                                                                                                                                                                                                                                                                                                                                                              left: "100%",
                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                      transition={{
                                                                                                                                                                                                                                                                                                                                                                                                    duration: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                  repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                ease: "easeInOut",
                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="absolute inset-0 bg-gradient-to-r from-transparent via-emerald-primary to-transparent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Status */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <m.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initial={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                opacity: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                opacity: [0, 1, 0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                duration: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex flex-col items-center gap-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[9px] font-mono text-emerald-primary/60 uppercase tracking-tighter">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Establishing Secure Link...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[8px] font-mono text-gray-700 uppercase">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Node: Algiers_HQ // v2.0.4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </m.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Scanline */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="absolute inset-0 bg-gradient-to-b from-transparent via-emerald-primary/[0.03] to-transparent h-[20%] w-full animate-scanline pointer-events-none" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Noise */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="noise-overlay opacity-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }