"use client";

import { m } from "framer-motion";

import Link from "next/link";

import {
  Terminal,
    Home,
      ChevronRight,
      } from "lucide-react";

      export default function NotFound() {
        return (
            <main className="relative min-h-screen flex items-center justify-center bg-background px-6 overflow-hidden">
                  {/* Background */}
                        <div className="absolute inset-0 bg-grid pointer-events-none opacity-40" />

                              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-emerald-primary/5 blur-[120px] rounded-full pointer-events-none" />

                                    <m.div
                                            initial={{
                                                      opacity: 0,
                                                                y: 20,
                                                                        }}
                                                                                animate={{
                                                                                          opacity: 1,
                                                                                                    y: 0,
                                                                                                            }}
                                                                                                                    className="relative z-10 text-center space-y-8 max-w-md"
                                                                                                                          >
                                                                                                                                  {/* Badge */}
                                                                                                                                          <div className="inline-flex items-center gap-2.5 px-3 py-1 rounded-full bg-red-500/10 border border-red-500/20 text-red-500 text-[10px] font-mono uppercase tracking-[0.2em]">
                                                                                                                                                    <span className="relative flex h-2 w-2">
                                                                                                                                                                <span className="absolute inline-flex h-full w-full rounded-full bg-red-500 opacity-75 animate-pulse"></span>

                                                                                                                                                                            <span className="relative inline-flex rounded-full h-2 w-2 bg-red-500"></span>
                                                                                                                                                                                      </span>

                                                                                                                                                                                                Protocol Breach
                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                {/* 404 */}
                                                                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                                                                  <h1 className="text-8xl md:text-9xl font-bold tracking-tighter text-transparent bg-clip-text bg-gradient-to-b from-white to-white/20">
                                                                                                                                                                                                                                              404
                                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                                                  <h2 className="text-lg md:text-xl font-mono text-gray-400 uppercase tracking-widest">
                                                                                                                                                                                                                                                                              Resource Not Found
                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                        {/* Message */}
                                                                                                                                                                                                                                                                                                                <p className="text-gray-500 text-sm md:text-base leading-relaxed font-mono max-w-xs mx-auto">
                                                                                                                                                                                                                                                                                                                          The requested operational node is
                                                                                                                                                                                                                                                                                                                                    unavailable or has been decommissioned.
                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                    {/* Button */}
                                                                                                                                                                                                                                                                                                                                                            <div className="pt-4">
                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                  href="/"
                                                                                                                                                                                                                                                                                                                                                                                              className="inline-flex items-center gap-3 px-8 py-4 bg-white text-black font-bold rounded-lg hover:bg-emerald-primary hover:text-white transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                    <Home size={18} />

                                                                                                                                                                                                                                                                                                                                                                                                                                Return to Base

                                                                                                                                                                                                                                                                                                                                                                                                                                            <ChevronRight size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="pt-12 flex items-center justify-center gap-4 border-t border-white/5 opacity-30">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Terminal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    size={14}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-emerald-primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-[10px] font-mono uppercase tracking-tighter">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System: Apollo-v14.2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </m.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Scanline */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-emerald-primary/5 to-transparent h-[10%] w-full animate-scanline pointer-events-none opacity-20" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }