"use client";

import { useState, useEffect, useRef, useCallback } from "react";

import { m, AnimatePresence } from "framer-motion";

import {
  FileText,
    Send,
      Terminal,
      } from "lucide-react";

      /**
       * CTRL + K Command Palette
        */
        export default function CommandPalette() {
          const [isOpen, setIsOpen] = useState(false);
            const [query, setQuery] = useState("");

              const inputRef = useRef<HTMLInputElement>(null);

                const togglePalette = useCallback(() => {
                    setIsOpen((prev) => !prev);
                        setQuery("");
                          }, []);

                            useEffect(() => {
                                const handleKeyDown = (e: KeyboardEvent) => {
                                      if (e.key === "k" && (e.ctrlKey || e.metaKey)) {
                                              e.preventDefault();
                                                      togglePalette();
                                                            }

                                                                  if (e.key === "Escape") {
                                                                          setIsOpen(false);
                                                                                }
                                                                                    };

                                                                                        window.addEventListener("keydown", handleKeyDown);

                                                                                            return () => {
                                                                                                  window.removeEventListener("keydown", handleKeyDown);
                                                                                                      };
                                                                                                        }, [togglePalette]);

                                                                                                          useEffect(() => {
                                                                                                              if (isOpen) {
                                                                                                                    inputRef.current?.focus();
                                                                                                                          document.body.style.overflow = "hidden";
                                                                                                                              } else {
                                                                                                                                    document.body.style.overflow = "unset";
                                                                                                                                        }

                                                                                                                                            return () => {
                                                                                                                                                  document.body.style.overflow = "unset";
                                                                                                                                                      };
                                                                                                                                                        }, [isOpen]);

                                                                                                                                                          const items = [
                                                                                                                                                              {
                                                                                                                                                                    name: "Download CV",
                                                                                                                                                                          icon: FileText,
                                                                                                                                                                                cmd: "cv",
                                                                                                                                                                                      action: () =>
                                                                                                                                                                                              window.open("/cv/mezili-amine-cv-en.pdf", "_blank"),
                                                                                                                                                                                                  },

                                                                                                                                                                                                      {
                                                                                                                                                                                                            name: "Initiate Mission Contact",
                                                                                                                                                                                                                  icon: Send,
                                                                                                                                                                                                                        cmd: "contact",
                                                                                                                                                                                                                              action: () => {
                                                                                                                                                                                                                                      document
                                                                                                                                                                                                                                                .getElementById("contact")
                                                                                                                                                                                                                                                          ?.scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                      ].filter((item) =>
                                                                                                                                                                                                                                                                          item.name.toLowerCase().includes(query.toLowerCase())
                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                  <AnimatePresence>
                                                                                                                                                                                                                                                                                        {isOpen && (
                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                          role="dialog"
                                                                                                                                                                                                                                                                                                                    aria-modal="true"
                                                                                                                                                                                                                                                                                                                              aria-label="Command Menu"
                                                                                                                                                                                                                                                                                                                                        className="fixed inset-0 z-[200] flex items-start justify-center pt-[15vh] px-4 bg-black/60 backdrop-blur-sm"
                                                                                                                                                                                                                                                                                                                                                  onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                    <m.div
                                                                                                                                                                                                                                                                                                                                                                                initial={{ opacity: 0, scale: 0.98, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                            animate={{ opacity: 1, scale: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                        exit={{ opacity: 0, scale: 0.98, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full max-w-lg bg-panel border border-white/10 rounded-xl overflow-hidden shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={(e) => e.stopPropagation()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3 p-4 border-b border-white/5 bg-white/[0.01]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Terminal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size={16}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-emerald-primary shrink-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ref={inputRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={query}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Execute operational command..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-transparent outline-none w-full text-sm font-mono text-white placeholder:text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="max-h-[300px] overflow-y-auto p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {items.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                items.map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={idx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item.action();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setIsOpen(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full flex items-center justify-between p-3 hover:bg-white/5 rounded-lg text-sm text-gray-400 hover:text-white transition-all group text-left"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div