"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, m } from "framer-motion";
import { Search, X } from "lucide-react";

export default function CommandPalette() {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setIsOpen((prev) => !prev);
      }

      if (e.key === "Escape") {
        setIsOpen(false);
      }
    };

    window.addEventListener("keydown", down);

    return () => {
      window.removeEventListener("keydown", down);
    };
  }, []);

  return (
    <AnimatePresence>
      {isOpen && (
        <m.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-start justify-center pt-32 px-4"
        >
          <m.div
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -20, opacity: 0 }}
            className="w-full max-w-2xl rounded-2xl border border-white/10 bg-panel/95 shadow-2xl overflow-hidden"
          >
            <div className="flex items-center gap-3 border-b border-white/10 px-4 py-4">
              <Search size={18} className="text-emerald-primary" />

              <input
                autoFocus
                type="text"
                placeholder="Search systems..."
                className="w-full bg-transparent outline-none text-sm text-white placeholder:text-gray-500"
              />

              <button
                onClick={() => setIsOpen(false)}
                className="text-gray-500 hover:text-white transition-colors"
              >
                <X size={18} />
              </button>
            </div>

            <div className="p-6 text-sm text-gray-400 font-mono">
              No indexed commands available.
            </div>
          </m.div>
        </m.div>
      )}
    </AnimatePresence>
  );
}                                                                                   };

                                                                                        window.addEventListener("keydown", handleKeyDown);

                                                                                            return () => {
                                                                                                  window.removeEventListener("keydown", handleKeyDown);
                                                                                                      };
                                                                                                        }, [togglePalette]);

                                                                                                          useEffect(() => {
                                                                                                              if (isOpen) {
                                                                                                                    inputRef.current?.focus();
                                                                                                                          document.body.style.overflow = "hidden";
                                                                                                                              } else {
                                                                                                                                    document.body.style.overflow = "unset";
                                                                                                                                        }

                                                                                                                                            return () => {
                                                                                                                                                  document.body.style.overflow = "unset";
                                                                                                                                                      };
                                                                                                                                                        }, [isOpen]);

                                                                                                                                                          const items = [
                                                                                                                                                              {
                                                                                                                                                                    name: "Download CV",
                                                                                                                                                                          icon: FileText,
                                                                                                                                                                                cmd: "cv",
                                                                                                                                                                                      action: () =>
                                                                                                                                                                                              window.open("/cv/mezili-amine-cv-en.pdf", "_blank"),
                                                                                                                                                                                                  },

                                                                                                                                                                                                      {
                                                                                                                                                                                                            name: "Initiate Mission Contact",
                                                                                                                                                                                                                  icon: Send,
                                                                                                                                                                                                                        cmd: "contact",
                                                                                                                                                                                                                              action: () => {
                                                                                                                                                                                                                                      document
                                                                                                                                                                                                                                                .getElementById("contact")
                                                                                                                                                                                                                                                          ?.scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                      ].filter((item) =>
                                                                                                                                                                                                                                                                          item.name.toLowerCase().includes(query.toLowerCase())
                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                  <AnimatePresence>
                                                                                                                                                                                                                                                                                        {isOpen && (
                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                          role="dialog"
                                                                                                                                                                                                                                                                                                                    aria-modal="true"
                                                                                                                                                                                                                                                                                                                              aria-label="Command Menu"
                                                                                                                                                                                                                                                                                                                                        className="fixed inset-0 z-[200] flex items-start justify-center pt-[15vh] px-4 bg-black/60 backdrop-blur-sm"
                                                                                                                                                                                                                                                                                                                                                  onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                    <m.div
                                                                                                                                                                                                                                                                                                                                                                                initial={{ opacity: 0, scale: 0.98, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                            animate={{ opacity: 1, scale: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                        exit={{ opacity: 0, scale: 0.98, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full max-w-lg bg-panel border border-white/10 rounded-xl overflow-hidden shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={(e) => e.stopPropagation()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3 p-4 border-b border-white/5 bg-white/[0.01]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Terminal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size={16}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-emerald-primary shrink-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ref={inputRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={query}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Execute operational command..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-transparent outline-none w-full text-sm font-mono text-white placeholder:text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="max-h-[300px] overflow-y-auto p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {items.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                items.map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={idx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item.action();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setIsOpen(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full flex items-center justify-between p-3 hover:bg-white/5 rounded-lg text-sm text-gray-400 hover:text-white transition-all group text-left"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
