"use client";

import { m } from "framer-motion";

import {
  Terminal,
    Shield,
      Cpu,
        ExternalLink,
        } from "lucide-react";

        export default function Footer() {
          const currentYear =
              new Date().getFullYear();

                return (
                    <footer className="relative py-12 px-6 border-t border-white/5 bg-background overflow-hidden">
                          <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
                                  {/* Branding */}
                                          <div className="flex flex-col items-center md:items-start gap-2">
                                                    <div className="flex items-center gap-2 text-white font-bold tracking-tighter">
                                                                <Terminal
                                                                              size={16}
                                                                                            className="text-emerald-primary"
                                                                                                        />

                                                                                                                    <span>MEZILI AMINE</span>
                                                                                                                              </div>

                                                                                                                                        <p className="text-[10px] font-mono text-gray-600 uppercase tracking-[0.2em]">
                                                                                                                                                    Operational Systems & Coordination
                                                                                                                                                              </p>
                                                                                                                                                                      </div>

                                                                                                                                                                              {/* Metadata */}
                                                                                                                                                                                      <div className="flex flex-wrap justify-center gap-6 md:gap-10">
                                                                                                                                                                                                <div className="flex items-center gap-2">
                                                                                                                                                                                                            <Shield
                                                                                                                                                                                                                          size={12}
                                                                                                                                                                                                                                        className="text-emerald-primary/40"
                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                <span className="text-[9px] font-mono text-gray-500 uppercase tracking-widest">
                                                                                                                                                                                                                                                                              Secured Transmission
                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                          <Cpu
                                                                                                                                                                                                                                                                                                                                        size={12}
                                                                                                                                                                                                                                                                                                                                                      className="text-emerald-primary/40"
                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                              <span className="text-[9px] font-mono text-gray-500 uppercase tracking-widest">
                                                                                                                                                                                                                                                                                                                                                                                            Next.js 14 Optimized
                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Right */}
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-col items-center md:items-end gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-[10px] font-mono text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                © {currentYear} // v2.0.4-STABLE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <m.a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="https://github.com/meziliamine"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex items-center gap-1.5 text-[9px] font-mono text-gray-500 hover:text-emerald-primary transition-colors uppercase tracking-tighter"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                whileHover={{ x: -2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Source Protocol

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ExternalLink size={10} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </m.a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-1/2 h-px bg-gradient-to-r from-transparent via-emerald-primary/20 to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }